### ISSUE TITLE
What's the point?

### ISSUE THREAD

**Issue by junekiwi** [Ashwin-op/GitHub-Follow-Bot#1]
> Somewhere, I read:
> 
>     One in ten people you follow will follow you back.
>     One in hundred people you follow will star your repos.
>     One in thousand people you follow will fork your repos.

You're following 9.5k people.

Is it really what we want GitHub to become? 
A place where bots randomly follow users and "star" projects?
 
People will star your repository if they find it useful.
They will fork it if they want to make changes.

A bot is a fun project, but please don't use it for real on GitHub.

**Comment by Ashwin-op** [comment]
Sure as I had mentioned before it's a fun project
